apiVersion: apps/v1
kind: Deployment
metadata:
  name: mot-eggs-deployment
  labels:
    app: mot-eggs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mot-eggs
  template:
    metadata:
      labels:
        app: mot-eggs
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 65534
      containers:
        - name: mot-eggs-app
          image: mot-eggs
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 4000Mi
              cpu: "3"
              ephemeral-storage: 4Gi
            requests:
              memory: 2000Mi
              cpu: "1"
              ephemeral-storage: 2Gi
          command:
            [
              "python",
              "gradio_app.py",
            ]
