apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- autoscale.yaml
- service.yaml
images:
- name: mot-eggs
  newName: eu.gcr.io/mot-demo-1/mot-eggs
  newTag: v0.0.9
