apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- autoscale.yaml
- service.yaml
images:
- name: mot-eggs
  newName: ghcr.io/hojland/mot-eggs/mot-eggs
  newTag: latest
