workerPoolSpecs:
  machineSpec:
    machineType: n1-highmem-4
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: eu.gcr.io/terraform-admin-goauto/mot-eggs-trainer:v0.0.1
    command:
      - bash
      - "-c"
      - |
        poetry run deepspeed --num_gpus=1 train.py --model_name_or_path=xlm-roberta-base --output_dir=mot-eggs --do_train=true --do_eval=true --per_device_train_batch_size=8 --per_device_eval_batch_size=8 --fp16=true --fp16_full_eval=true --logging_steps=20 --num_train_epochs=12 --logging_dir=logs --evaluation_strategy=steps --eval_steps=200 --save_strategy=steps --save_steps=200 --save_total_limit=3 --deepspeed=train_configs/ds_config.json --learning_rate=1e-05 --weight_decay=1.0e-01 --adam_beta1=0.90 --adam_beta2=0.999 --warmup_ratio=0.1 --train_val_test_size=[0.9,0.03,0.07] --remove_unused_columns=false
    env:
      - name: POSTGREST_URL
        value: <POSTGREST_URL>
      - name: JWT_TOKEN
        value: <JWT_TOKEN>
      - name: SAGA_TOKEN
        value: <JWT_TOKEN>
      - name: WANDB_API_KEY
        value: <WANDB_API_KEY>
      - name: CONFLUENCE_API_TOKEN
        value: <CONFLUENCE_API_TOKEN>
enableWebAccess: true
baseOutputDirectory:
  outputUriPrefix: "gs://vertex-model-artifacts/mot-eggs-1"
network: projects/594815127375/global/networks/vpc
serviceAccount: default-vm-service-account@ml-training-prod-goauto-1.iam.gserviceaccount.com
