apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - autoscale.yaml
  - app_service.yaml
  - gateway.yaml
  - virtualservice.yaml
images:
  - name: mot-eggs
    newName: eu.gcr.io/terraform-admin-goauto/mot-eggs
    newTag: v0.0.1