name: build

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  PROJECT_ID: mot-demo-1
  IMAGE: mot-eggs
  GKE_CLUSTER: demo
  GKE_ZONE: europe-west4a
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

jobs:
  tag_and_release:
    name: tag_and_release
    runs-on: ubuntu-latest
    #    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      release_tag: ${{ steps.fetch-latest-release.outputs.latest-release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: fetch-latest-release
        run: |
          git fetch --tags
          export LATEST_RELEASE_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=latest-release::$(echo $LATEST_RELEASE_VERSION)"
          echo The latest release version is \"$LATEST_RELEASE_VERSION\".
        shell: bash

  build_and_push:
    runs-on: ubuntu-latest
    needs: [tag_and_release]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - id: repo_string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Set docker name
        id: vars
        run: echo ::set-output name=docker_name::docker.pkg.github.com/${{ steps.repo_string.outputs.lowercase }}/${IMAGE}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.docker_name }}:${{needs.tag_and_release.outputs.release_tag}}
      - name: Log into registry again
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Retag to latest
        run: |
          docker pull ${{ steps.vars.outputs.docker_name }}:${{needs.tag_and_release.outputs.release_tag}}
          docker tag ${{ steps.vars.outputs.docker_name }}:${{needs.tag_and_release.outputs.release_tag}} ${{ steps.vars.outputs.docker_name }}:latest
          docker push ${{ steps.vars.outputs.docker_name }}:latest